services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  todoapp.api:
    image: ${DOCKER_REGISTRY-}todoappapi
    build:
      context: .
      dockerfile: TodoApp.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=todo_db;Username=todo_user;Password=todo_pass"
      Redis__ConnectionString: "redis:6379"
    depends_on:
      - postgres
      - redis

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todoapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  redisdata:
  pgadmin_data: